/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#7b5455',
        'on-primary': '#ffffff',
        'primary-container': '#f4c2c2',
        'on-primary-container': '#734e4e',
        'primary-fixed': '#ffdad9',
        'primary-fixed-dim': '#ecbaba',
        'on-primary-fixed': '#2f1314',
        'on-primary-fixed-variant': '#613d3e',
        'inverse-primary': '#ecbaba',
        'secondary': '#5c5d6e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1e1f5',
        'on-secondary-container': '#626374',
        'secondary-fixed': '#e1e1f5',
        'secondary-fixed-dim': '#c5c5d8',
        'on-secondary-fixed': '#191b29',
        'on-secondary-fixed-variant': '#444655',
        'tertiary': '#5f5f59',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d0cec7',
        'on-tertiary-container': '#585852',
        'tertiary-fixed': '#e4e3db',
        'tertiary-fixed-dim': '#c8c7bf',
        'on-tertiary-fixed': '#1b1c17',
        'on-tertiary-fixed-variant': '#474742',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fff8f6',
        'on-background': '#1e1b19',
        'surface': '#fff8f6',
        'surface-dim': '#e1d8d5',
        'surface-bright': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf2ef',
        'surface-container': '#f5ece9',
        'surface-container-high': '#efe6e3',
        'surface-container-highest': '#e9e1de',
        'on-surface': '#1e1b19',
        'on-surface-variant': '#504444',
        'outline': '#827473',
        'outline-variant': '#d4c2c2',
        'surface-tint': '#7b5455',
        'inverse-surface': '#342f2e',
        'inverse-on-surface': '#f8efec',
        'surface-variant': '#e9e1de',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'base': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'container-padding': '20px',
        'touch-target': '44px',
      },
      fontFamily: {
        'display': ['"Playfair Display"', 'serif'],
        'headline': ['"Playfair Display"', 'serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
      boxShadow: {
        'soft': '0px 10px 30px rgba(74, 69, 67, 0.05)',
        'card': '0px 4px 12px rgba(74, 69, 67, 0.03)',
        'nav': '0px -2px 10px rgba(74, 69, 67, 0.05)',
      },
    },
  },
  plugins: [],
}
